CREATE DATABASE siddhi;
USE siddhi;

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
gender ENUM('Male', 'Female', 'Other')
);

SELECT * FROM users;

RENAME TABLE users TO kemcho;

RENAME TABLE kemcho to users;

ALTER TABLE users ADD COLUMN is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT current_timestamp;
ALTER TABLE users DROP COLUMN is_active;
ALTER TABLE users MODIFY COLUMN name VARCHAR(150);
ALTER TABLE users MODIFY COLUMN ID int AFTER name;